/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EIOSAPPIRATER_AUTODEFS_H
#define S3EIOSAPPIRATER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSAPPIRATER_NAME "s3eIOSAppirater"
#define S3E_EXT_IOSAPPIRATER_HASH 0xf2eb1843

#endif /* !S3EIOSAPPIRATER_AUTODEFS_H */
