/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eIOSAppirater.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eIOSAppiraterParams_t)(int appId, int usesUntilPrompt, int daysUntilPrompt, int daysRemindLater, int nrSignificantEvents, const char * dlg_title, const char * dlg_text, const char * dlg_rate_button, const char * remind_dlg_title, const char * remind_dlg_text);
typedef       void(*s3eIOSAppiraterAppLaunched_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterAppEnteredForeground_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterUserDidSignificantEvent_t)(bool canPromptForRating);
typedef       void(*s3eIOSAppiraterRateApp_t)();

/**
 * struct that gets filled in by s3eIOSAppiraterRegister
 */
typedef struct s3eIOSAppiraterFuncs
{
    s3eIOSAppiraterParams_t m_s3eIOSAppiraterParams;
    s3eIOSAppiraterAppLaunched_t m_s3eIOSAppiraterAppLaunched;
    s3eIOSAppiraterAppEnteredForeground_t m_s3eIOSAppiraterAppEnteredForeground;
    s3eIOSAppiraterUserDidSignificantEvent_t m_s3eIOSAppiraterUserDidSignificantEvent;
    s3eIOSAppiraterRateApp_t m_s3eIOSAppiraterRateApp;
} s3eIOSAppiraterFuncs;

static s3eIOSAppiraterFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf2eb1843, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eIOSAppirater");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf2eb1843, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eIOSAppiraterAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void s3eIOSAppiraterParams(int appId, int usesUntilPrompt, int daysUntilPrompt, int daysRemindLater, int nrSignificantEvents, const char * dlg_title, const char * dlg_text, const char * dlg_rate_button, const char * remind_dlg_title, const char * remind_dlg_text)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[0] func: s3eIOSAppiraterParams"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSAppiraterParams(appId, usesUntilPrompt, daysUntilPrompt, daysRemindLater, nrSignificantEvents, dlg_title, dlg_text, dlg_rate_button, remind_dlg_title, remind_dlg_text);
}

void s3eIOSAppiraterAppLaunched(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[1] func: s3eIOSAppiraterAppLaunched"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSAppiraterAppLaunched(canPromptForRating);
}

void s3eIOSAppiraterAppEnteredForeground(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[2] func: s3eIOSAppiraterAppEnteredForeground"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSAppiraterAppEnteredForeground(canPromptForRating);
}

void s3eIOSAppiraterUserDidSignificantEvent(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[3] func: s3eIOSAppiraterUserDidSignificantEvent"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSAppiraterUserDidSignificantEvent(canPromptForRating);
}

void s3eIOSAppiraterRateApp()
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater[4] func: s3eIOSAppiraterRateApp"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSAppiraterRateApp();
}
