/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eIOSAppirater_autodefs.h"
#include "s3eEdk.h"
#include "s3eIOSAppirater.h"
//Declarations of Init and Term functions
extern s3eResult s3eIOSAppiraterInit();
extern void s3eIOSAppiraterTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void s3eIOSAppiraterAppLaunched_wrap(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater func on main thread: s3eIOSAppiraterAppLaunched"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eIOSAppiraterAppLaunched, 1, canPromptForRating);
}

static void s3eIOSAppiraterAppEnteredForeground_wrap(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater func on main thread: s3eIOSAppiraterAppEnteredForeground"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eIOSAppiraterAppEnteredForeground, 1, canPromptForRating);
}

static void s3eIOSAppiraterUserDidSignificantEvent_wrap(bool canPromptForRating)
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater func on main thread: s3eIOSAppiraterUserDidSignificantEvent"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eIOSAppiraterUserDidSignificantEvent, 1, canPromptForRating);
}

static void s3eIOSAppiraterRateApp_wrap()
{
    IwTrace(IOSAPPIRATER_VERBOSE, ("calling s3eIOSAppirater func on main thread: s3eIOSAppiraterRateApp"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eIOSAppiraterRateApp, 0);
}

#define s3eIOSAppiraterAppLaunched s3eIOSAppiraterAppLaunched_wrap
#define s3eIOSAppiraterAppEnteredForeground s3eIOSAppiraterAppEnteredForeground_wrap
#define s3eIOSAppiraterUserDidSignificantEvent s3eIOSAppiraterUserDidSignificantEvent_wrap
#define s3eIOSAppiraterRateApp s3eIOSAppiraterRateApp_wrap

#endif

void s3eIOSAppiraterRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[5];
    funcPtrs[0] = (void*)s3eIOSAppiraterParams;
    funcPtrs[1] = (void*)s3eIOSAppiraterAppLaunched;
    funcPtrs[2] = (void*)s3eIOSAppiraterAppEnteredForeground;
    funcPtrs[3] = (void*)s3eIOSAppiraterUserDidSignificantEvent;
    funcPtrs[4] = (void*)s3eIOSAppiraterRateApp;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[5] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eIOSAppirater", funcPtrs, sizeof(funcPtrs), flags, s3eIOSAppiraterInit, s3eIOSAppiraterTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eIOSAppiraterStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eIOSAppiraterRegisterExt;
    return 0;
}

int g_s3eIOSAppiraterVal = s3eIOSAppiraterStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eIOSAppiraterRegisterExt();
}
#endif

#endif
